stages:
  - tests
  - build
  - dev
  - staging
  - prod

tests:
  stage: tests
  image: binkhq/python:3.9
  before_script:
    - apt-get update
    - apt-get -y install gcc
    - pip install pipenv
    - pipenv install --dev --system --deploy --ignore-pipfile
  script:
    - pytest --verbose --cov app --cov-report term-missing app/tests/unit

complexity:
  stage: tests
  image: binkhq/python:3.9
  before_script:
    - pip install xenon
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

style:
  stage: tests
  image: binkhq/python:3.9
  before_script:
    - pip install flake8 black
  script:
    - flake8 && black --line-length 120 --check .

type-check:
  stage: tests
  image: binkhq/python:3.9
  before_script:
    - pip install mypy
  script:
    - mypy --ignore-missing-imports app

dev:
  stage: dev
  environment:
    name: dev
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="develop-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/zephyrus:$CTAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/zephyrus:$CTAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/zephyrus:$CTAG"
  only:
    - develop

build-master:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/zephyrus:$CI_COMMIT_TAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/zephyrus:$CI_COMMIT_TAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/zephyrus:$CI_COMMIT_TAG"
  only:
    - tags

tag-staging:
  stage: staging
  image: binkops.azurecr.io/tagbot:latest
  environment:
    name: staging
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/zephyrus:$CI_COMMIT_TAG" --tag "staging-$CI_COMMIT_TAG"
  only:
    - tags

tag-prod:
  stage: prod
  image: binkops.azurecr.io/tagbot:latest
  environment:
    name: prod
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/zephyrus:$CI_COMMIT_TAG" --tag "prod-$CI_COMMIT_TAG"
  when: manual
  only:
    - tags
