#! /bin/bash

set -euo pipefail

cyan=$(tput bold)$(tput setab 4)$(tput setaf 7)
white=$(tput bold)$(tput setab 7)$(tput setaf 0)
normal=$(tput sgr0)

p() {
    env printf "${cyan} \342\204\271 ${white} ${1} ${normal}\n"
}
