name: ci

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  release:
    types: [ published ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install pipenv
      - run: pipenv install --dev --system --deploy --ignore-pipfile
      - run: pytest --verbose --cov app --cov-report=xml --junitxml=report.xml app/tests/unit
      - run: xenon --max-average A --max-modules B --max-absolute B .
      - run: mypy --ignore-missing-imports app
      - run: flake8 .
      - run: black --line-length=120 --check .
      - run: isort --check --line-length 120 --profile black .
  create_dev_release:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    name: create_dev_release
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=date::$(date +'%FT%H%M%SZ')"
        id: date
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            binkcore.azurecr.io/zephyrus:${{ steps.date.outputs.date }}
            binkcore.azurecr.io/zephyrus:latest
  create_tag_release:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: create_tag_release
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v2
      - name: tag_check
        run: |
          if ! [[ ${{ github.event.release.tag_name }} =~ [0-9]+.[0-9]+.[0-9]+ ]]; then
            exit 1;
          fi
      - uses: docker/login-action@v1
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            binkcore.azurecr.io/zephyrus:${{ github.event.release.tag_name }}
            binkcore.azurecr.io/zephyrus:staging-${{ github.event.release.tag_name }}
            binkcore.azurecr.io/zephyrus:staging
