name: tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install poetry
      - run: poetry install
      - run: poetry run scripts/cibuild
