name: tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: pip install poetry
      - run: poetry install --dev --system --deploy --ignore-pipfile
      - run: pytest --verbose --cov app --cov-report=xml --junitxml=report.xml app/tests/unit
      - run: xenon --max-average A --max-modules B --max-absolute B .
      - run: mypy --ignore-missing-imports app
      - run: flake8 .
      - run: black --line-length=120 --check .
      - run: isort --check --line-length 120 --profile black .
